import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import ReactQueryProvider from './_providers/react-query';
import { Footer, Header } from '@/shared';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable} antialiased
          bg-gray-50 text-gray-900
          min-h-screen
          flex flex-col
          selection:bg-green-500 selection:text-white
        `}
      >
        <ReactQueryProvider>
          <Header />
          <main className="flex-grow max-w-7xl mx-auto w-full px-6 py-8 md:py-8">
            {children}
          </main>
          <Footer />
        </ReactQueryProvider>
      </body>
    </html>
  );
}
